import renewable from "./renewable.png";

// data.js
export const combinedData = [
  // Solar Farm Data
  {
    id: 1,
    type: "solar",
    title: "BLUEGRASS",
    voltage: "33kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 2,
    type: "solar",
    title: "CULCAIRN",
    voltage: "33kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 3,
    type: "solar",
    title: "EDENVALE",
    voltage: "275kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 4,
    type: "solar",
    title: "EVERLEIGH",
    voltage: "275kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 5,
    type: "solar",
    title: "FRASER",
    voltage: "33kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 6,
    type: "solar",
    title: "KIAMAL",
    voltage: "220kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 7,
    type: "solar",
    title: "RICHMOND",
    voltage: "330/33kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 8,
    type: "solar",
    title: "RICHMOND",
    voltage: "33kV",
    description: "SOLAR SWITCHING SUBSTATION",
    img: renewable,
  },
  {
    id: 9,
    type: "solar",
    title: "WALLA WALLA",
    voltage: "33kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 10,
    type: "solar",
    title: "WALL WALL HF",
    voltage: "33kV",
    description: "HARMONIC FILTER SUBSTATION",
    img: renewable,
  },
  {
    id: 11,
    type: "solar",
    title: "WELLINGTON",
    voltage: "330kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 12,
    type: "solar",
    title: "WUGHNU",
    voltage: "33kV",
    description: "SOLAR FARM SUBSTATION",
    img: renewable,
  },

  // Battery Data
  {
    id: 13,
    type: "battery",
    title: "BLACKTOP",
    voltage: "100MW",
    description: "BESS",
    img: renewable,
  },
  {
    id: 14,
    type: "battery",
    title: "DENILIQUIN",
    voltage: "100MW",
    description: "BESS",
    img: renewable,
  },
  {
    id: 15,
    type: "battery",
    title: "DIREK",
    voltage: "20MW",
    description: "BESS",
    img: renewable,
  },
  {
    id: 16,
    type: "battery",
    title: "FINLEY",
    voltage: "100MW",
    description: "BESS",
    img: renewable,
  },
  {
    id: 17,
    type: "battery",
    title: "FOSTER",
    voltage: "70MW",
    description: "BESS",
    img: renewable,
  },
  {
    id: 18,
    type: "battery",
    title: "JINDERA",
    voltage: "250MW",
    description: "BESS",
    img: renewable,
  },
  {
    id: 19,
    type: "battery",
    title: "PENFIELD",
    voltage: "20MW",
    description: "BESS",
    img: renewable,
  },
  {
    id: 20,
    type: "battery",
    title: "WHYLAA",
    voltage: "100MW",
    description: "BESS",
    img: renewable,
  },

  // Wind Farm Data
  {
    id: 21,
    type: "wind",
    title: "BOOMER",
    voltage: "275kV",
    description: "WIND FARM SUBSTATION",
    img: renewable,
  },
  {
    id: 22,
    type: "wind",
    title: "BOOMER",
    voltage: "275kV",
    description: "WIND FARM SWITCHING SUBSTATION",
    img: renewable,
  },
  // Add more objects as needed
];
